### ISSUE TITLE
Recent issue with OW streams, Index out of range in Farmer.update_data()

### ISSUE THREAD

**Issue by gab51299** [ucarno/ow-league-tokens#40] opened 2023-03-26 04:57 UTC
Getting the following error for recent OWL streams:

`Task exception was never retrieved
future: <Task finished name='Task-5' coro=<Farmer.update_data() done, defined at farmer.py:112> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "farmer.py", line 116, in update_data
IndexError: list index out of range`

I'm not familiar with your code, but the formatting of the stream data that the new streams are sending may be different or new, and wouldn't work. Omnic Rewards is getting a similar formatting issue, maybe they added a few parameters hence the index error. 
![image_2023-03-26_125736468](https://user-images.githubusercontent.com/48877819/227756173-54f99040-f34c-4696-939d-20ef2e3bc8a2.png)

**Comment by ucarno** [comment] 2023-04-09 15:41
Closing as duplicate of https://github.com/ucarno/ow-league-tokens/issues/38

**Closed by ucarno** 2023-04-09 15:41 UTC
